name: Build
on:
  push:
    branches:
    - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=./nix/pkgs.nix
    - uses: cachix/cachix-action@v8
      with:
        name: evanrelf
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build
