name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build-8.6.5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        name: Checkout
      - uses: cachix/install-nix-action@v12
        name: Install Nix
        with:
          nix_path: nixpkgs=./nix/pkgs.nix
      - uses: cachix/cachix-action@v8
        name: Set up Cachix
        with:
          name: evanrelf
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: |
          nix-build --attr drama --argstr ghcVersion "ghc865"
        name: nix-build

  build-8.8.4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        name: Checkout
      - uses: cachix/install-nix-action@v12
        name: Install Nix
        with:
          nix_path: nixpkgs=./nix/pkgs.nix
      - uses: cachix/cachix-action@v8
        name: Set up Cachix
        with:
          name: evanrelf
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: |
          nix-build --attr drama --argstr ghcVersion "ghc884"
        name: nix-build

  build-8.10.3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        name: Checkout
      - uses: cachix/install-nix-action@v12
        name: Install Nix
        with:
          nix_path: nixpkgs=./nix/pkgs.nix
      - uses: cachix/cachix-action@v8
        name: Set up Cachix
        with:
          name: evanrelf
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: |
          nix-build
        name: nix-build
