name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        name: Checkout
      - uses: cachix/install-nix-action@v12
        name: Install Nix
        with:
          nix_path: nixpkgs=./nix/pkgs.nix
      - uses: cachix/cachix-action@v8
        name: Set up Cachix
        with:
          name: evanrelf
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: |
          nix-build --attr drama --argstr ghcVersion "ghc865"
          nix-build --attr drama --argstr ghcVersion "ghc884"
          nix-build --attr drama --argstr ghcVersion "ghc8103"
          nix-build
        name: nix-build
